/**
 * workbench.js — every VS Code UI surface, derived from the palette.
 *
 * Rules of the house:
 *   • Chrome recedes, the canvas leads. The side bar and activity bar sit
 *     ~4 L* below the editor so your eye lands on code, not furniture.
 *   • Borders are alpha overlays, never opaque lines, so panes read as folds in
 *     one surface instead of a grid of boxes.
 *   • Accents are used for state (active, dirty, error), never for decoration.
 *   • Nothing large is ever bright: no filled accent panels, no gradients.
 */

'use strict';

module.exports = function workbench(p) {
  const { ui, base, bright, muted, status, a } = p;
  const light = p.isLight;

  // Contrast-correct text to sit on top of a filled accent (badges, buttons).
  const onAccent = light ? ui.editor : ui.deep;
  const border = a(ui.line, light ? 0.6 : 0.55);
  const borderSoft = a(ui.line, light ? 0.35 : 0.32);
  const shadow = a(light ? ui.subtle : '#000000', light ? 0.14 : 0.42);

  return {
    /* ── base ─────────────────────────────────────────────────────────── */
    focusBorder: a(base.rose, 0.55),
    foreground: ui.dim,
    disabledForeground: a(ui.dim, 0.5),
    descriptionForeground: ui.comment,
    errorForeground: status.error,
    'widget.border': borderSoft,
    'widget.shadow': shadow,
    'selection.background': a(base.azure, 0.35),
    'icon.foreground': ui.dim,
    'sash.hoverBorder': a(base.rose, 0.6),

    /* ── window ───────────────────────────────────────────────────────── */
    'window.activeBorder': a(ui.line, 0.8),
    'window.inactiveBorder': borderSoft,

    /* ── text (markdown previews, walkthroughs, hovers) ───────────────── */
    'textBlockQuote.background': a(ui.raised, 0.6),
    'textBlockQuote.border': a(base.rose, 0.5),
    'textCodeBlock.background': a(ui.raised, 0.7),
    'textLink.activeForeground': bright.azure,
    'textLink.foreground': base.azure,
    'textPreformat.foreground': base.gold,
    'textPreformat.background': a(base.gold, 'faint'),
    'textSeparator.foreground': ui.line,

    /* ── buttons, badges, toggles ─────────────────────────────────────── */
    'button.background': light ? base.violet : muted.violet,
    'button.foreground': light ? ui.editor : ui.bright,
    'button.hoverBackground': light ? bright.violet : base.violet,
    'button.border': a(base.violet, 0.35),
    'button.secondaryBackground': ui.overlay,
    'button.secondaryForeground': ui.fg,
    'button.secondaryHoverBackground': ui.line,
    'checkbox.background': ui.overlay,
    'checkbox.foreground': ui.fg,
    'checkbox.border': border,
    'checkbox.selectBackground': a(base.violet, 'medium'),
    'checkbox.selectBorder': base.violet,
    'radio.activeBackground': a(base.violet, 'medium'),
    'radio.activeBorder': base.violet,
    'radio.activeForeground': ui.bright,
    'radio.inactiveBorder': border,
    'badge.background': a(base.rose, light ? 0.22 : 0.28),
    'badge.foreground': light ? bright.rose : bright.rose,
    'extensionButton.prominentBackground': light ? base.violet : muted.violet,
    'extensionButton.prominentForeground': light ? ui.editor : ui.bright,
    'extensionButton.prominentHoverBackground': light ? bright.violet : base.violet,
    'extensionBadge.remoteBackground': a(base.teal, 0.3),
    'extensionBadge.remoteForeground': bright.teal,
    'extensionIcon.starForeground': base.gold,
    'extensionIcon.verifiedForeground': base.teal,
    'extensionIcon.preReleaseForeground': base.violet,
    'extensionIcon.sponsorForeground': base.rose,

    /* ── inputs & dropdowns ───────────────────────────────────────────── */
    'input.background': light ? ui.editor : a(ui.deep, 0.55),
    'input.foreground': ui.fg,
    'input.border': border,
    'input.placeholderForeground': a(ui.comment, 0.85),
    'inputOption.activeBackground': a(base.rose, 'medium'),
    'inputOption.activeBorder': a(base.rose, 0.6),
    'inputOption.activeForeground': bright.rose,
    'inputOption.hoverBackground': a(ui.line, 0.4),
    'inputValidation.errorBackground': p.mix(ui.overlay, status.error, light ? 0.12 : 0.2),
    'inputValidation.errorBorder': status.error,
    'inputValidation.errorForeground': ui.fg,
    'inputValidation.infoBackground': p.mix(ui.overlay, status.info, light ? 0.12 : 0.2),
    'inputValidation.infoBorder': status.info,
    'inputValidation.infoForeground': ui.fg,
    'inputValidation.warningBackground': p.mix(ui.overlay, status.warning, light ? 0.12 : 0.2),
    'inputValidation.warningBorder': status.warning,
    'inputValidation.warningForeground': ui.fg,
    'dropdown.background': ui.overlay,
    'dropdown.listBackground': ui.overlay,
    'dropdown.foreground': ui.fg,
    'dropdown.border': border,

    /* ── scrollbars & sliders ─────────────────────────────────────────── */
    'scrollbar.shadow': a(ui.deep, light ? 0.18 : 0.5),
    'scrollbarSlider.background': a(ui.subtle, 0.28),
    'scrollbarSlider.hoverBackground': a(ui.subtle, 0.45),
    'scrollbarSlider.activeBackground': a(base.rose, 0.45),
    'progressBar.background': base.rose,

    /* ── lists & trees ────────────────────────────────────────────────── */
    'list.activeSelectionBackground': a(base.violet, light ? 0.16 : 0.2),
    'list.activeSelectionForeground': ui.bright,
    'list.activeSelectionIconForeground': bright.violet,
    'list.inactiveSelectionBackground': a(ui.line, 0.32),
    'list.inactiveSelectionForeground': ui.fg,
    'list.hoverBackground': a(ui.line, 0.22),
    'list.hoverForeground': ui.fg,
    'list.focusBackground': a(base.violet, light ? 0.14 : 0.18),
    'list.focusForeground': ui.bright,
    'list.focusOutline': a(base.rose, 0.4),
    'list.highlightForeground': bright.rose,
    'list.focusHighlightForeground': bright.rose,
    'list.dropBackground': a(base.violet, 'medium'),
    'list.errorForeground': status.error,
    'list.warningForeground': status.warning,
    'list.invalidItemForeground': a(status.error, 0.7),
    'list.deemphasizedForeground': ui.comment,
    'listFilterWidget.background': ui.overlay,
    'listFilterWidget.outline': base.rose,
    'listFilterWidget.noMatchesOutline': status.error,
    'listFilterWidget.shadow': shadow,
    'tree.indentGuidesStroke': a(ui.subtle, 0.35),
    'tree.inactiveIndentGuidesStroke': a(ui.subtle, 0.18),
    'tree.tableColumnsBorder': borderSoft,
    'tree.tableOddRowsBackground': a(ui.raised, 0.4),

    /* ── activity bar ─────────────────────────────────────────────────── */
    'activityBar.background': ui.chrome,
    'activityBar.foreground': ui.fg,
    'activityBar.inactiveForeground': a(ui.subtle, light ? 0.9 : 0.8),
    'activityBar.border': borderSoft,
    'activityBar.activeBorder': base.rose,
    'activityBar.activeBackground': a(base.rose, 'faint'),
    'activityBar.activeFocusBorder': bright.rose,
    'activityBarBadge.background': light ? base.rose : muted.rose,
    'activityBarBadge.foreground': light ? ui.editor : ui.bright,
    'activityBarTop.foreground': ui.fg,
    'activityBarTop.inactiveForeground': a(ui.subtle, 0.8),
    'activityBarTop.activeBorder': base.rose,
    'activityBarTop.dropBorder': base.rose,
    'activityBarTop.background': ui.chrome,

    /* ── side bar ─────────────────────────────────────────────────────── */
    'sideBar.background': ui.surface,
    'sideBar.foreground': ui.dim,
    'sideBar.border': borderSoft,
    'sideBar.dropBackground': a(base.violet, 'soft'),
    'sideBarTitle.foreground': ui.fg,
    'sideBarTitle.background': ui.surface,
    'sideBarSectionHeader.background': a(ui.deep, light ? 0.35 : 0.35),
    'sideBarSectionHeader.foreground': ui.fg,
    'sideBarSectionHeader.border': borderSoft,
    'sideBarActivityBarTop.border': borderSoft,
    'sideBarStickyScroll.background': ui.surface,
    'sideBarStickyScroll.border': borderSoft,
    'sideBarStickyScroll.shadow': shadow,

    /* ── editor groups & tabs ─────────────────────────────────────────── */
    'editorGroup.border': borderSoft,
    'editorGroup.dropBackground': a(base.violet, 'soft'),
    'editorGroup.emptyBackground': ui.editor,
    'editorGroupHeader.noTabsBackground': ui.surface,
    'editorGroupHeader.tabsBackground': ui.surface,
    'editorGroupHeader.tabsBorder': borderSoft,
    'editorGroupHeader.border': borderSoft,
    'editorGroup.dropIntoPromptBackground': ui.overlay,
    'editorGroup.dropIntoPromptForeground': ui.fg,
    'tab.activeBackground': ui.editor,
    'tab.activeForeground': ui.bright,
    'tab.activeBorder': ui.editor,
    'tab.activeBorderTop': base.rose,
    'tab.inactiveBackground': ui.surface,
    'tab.inactiveForeground': a(ui.dim, 0.62),
    'tab.border': borderSoft,
    'tab.hoverBackground': a(ui.raised, 0.7),
    'tab.hoverForeground': ui.fg,
    'tab.hoverBorder': a(base.rose, 0.35),
    'tab.unfocusedActiveBackground': ui.editor,
    'tab.unfocusedActiveForeground': ui.dim,
    'tab.unfocusedActiveBorderTop': a(base.rose, 0.35),
    'tab.unfocusedInactiveBackground': ui.surface,
    'tab.unfocusedInactiveForeground': a(ui.dim, 0.45),
    'tab.unfocusedHoverBackground': a(ui.raised, 0.5),
    'tab.lastPinnedBorder': a(ui.line, 0.7),
    'tab.dragAndDropBorder': base.rose,
    'tab.activeModifiedBorder': base.gold,
    'tab.inactiveModifiedBorder': a(base.gold, 0.45),
    'tab.unfocusedActiveModifiedBorder': a(base.gold, 0.6),
    'tab.unfocusedInactiveModifiedBorder': a(base.gold, 0.3),
    'editorPane.background': ui.editor,

    /* ── the canvas ───────────────────────────────────────────────────── */
    'editor.background': ui.editor,
    'editor.foreground': ui.fg,
    'editorLineNumber.foreground': a(ui.subtle, light ? 0.85 : 0.75),
    'editorLineNumber.activeForeground': ui.fg,
    'editorLineNumber.dimmedForeground': a(ui.subtle, 0.45),
    'editorCursor.foreground': light ? base.rose : bright.rose,
    'editorCursor.background': ui.editor,
    'editorMultiCursor.primary.foreground': light ? base.rose : bright.rose,
    'editorMultiCursor.secondary.foreground': base.violet,
    'editor.selectionBackground': a(base.azure, light ? 0.24 : 0.26),
    'editor.selectionForeground': null,
    'editor.inactiveSelectionBackground': a(base.azure, light ? 0.12 : 0.13),
    'editor.selectionHighlightBackground': a(base.azure, light ? 0.1 : 0.12),
    'editor.selectionHighlightBorder': a(base.azure, 0.25),
    'editor.wordHighlightBackground': a(base.violet, light ? 0.12 : 0.16),
    'editor.wordHighlightBorder': a(base.violet, 0.28),
    'editor.wordHighlightStrongBackground': a(base.green, light ? 0.12 : 0.16),
    'editor.wordHighlightStrongBorder': a(base.green, 0.28),
    'editor.wordHighlightTextBackground': a(base.azure, 0.1),
    'editor.findMatchBackground': a(base.amber, light ? 0.3 : 0.34),
    'editor.findMatchBorder': a(base.amber, 0.75),
    'editor.findMatchHighlightBackground': a(base.amber, light ? 0.16 : 0.18),
    'editor.findMatchHighlightBorder': a(base.amber, 0.32),
    'editor.findRangeHighlightBackground': a(ui.line, 0.28),
    'editor.findRangeHighlightBorder': '#00000000',
    'editor.hoverHighlightBackground': a(base.azure, 0.14),
    'editor.lineHighlightBackground': light ? a(ui.raised, 0.75) : ui.raised,
    'editor.lineHighlightBorder': '#00000000',
    'editor.rangeHighlightBackground': a(base.violet, 0.1),
    'editor.rangeHighlightBorder': '#00000000',
    'editor.symbolHighlightBackground': a(base.teal, 0.16),
    'editor.symbolHighlightBorder': a(base.teal, 0.3),
    'editor.foldBackground': a(base.azure, 0.08),
    'editor.foldPlaceholderForeground': ui.comment,
    'editorWhitespace.foreground': a(ui.subtle, light ? 0.4 : 0.32),
    'editorIndentGuide.background1': a(ui.subtle, light ? 0.28 : 0.22),
    'editorIndentGuide.activeBackground1': a(ui.subtle, light ? 0.6 : 0.55),
    // deprecated keys, kept so the engine floor (1.74) still shows guides
    'editorIndentGuide.background': a(ui.subtle, light ? 0.28 : 0.22),
    'editorIndentGuide.activeBackground': a(ui.subtle, light ? 0.6 : 0.55),
    'editorInlayHint.background': a(ui.overlay, light ? 0.55 : 0.55),
    'editorInlayHint.foreground': ui.comment,
    'editorInlayHint.typeBackground': a(ui.overlay, 0.55),
    'editorInlayHint.typeForeground': muted.gold,
    'editorInlayHint.parameterBackground': a(ui.overlay, 0.55),
    'editorInlayHint.parameterForeground': muted.amber,
    'editorRuler.foreground': a(ui.line, 0.5),
    'editorCodeLens.foreground': a(ui.comment, 0.9),
    'editorLightBulb.foreground': base.gold,
    'editorLightBulbAutoFix.foreground': base.green,
    'editorLightBulbAi.foreground': base.violet,
    'editorBracketMatch.background': a(base.teal, 0.18),
    'editorBracketMatch.border': a(base.teal, 0.6),
    'editorLink.activeForeground': bright.azure,
    'editorUnicodeHighlight.background': a(base.amber, 0.14),
    'editorUnicodeHighlight.border': a(base.amber, 0.5),
    'editor.linkedEditingBackground': a(base.rose, 0.12),
    'editorGhostText.foreground': a(ui.comment, light ? 0.85 : 0.8),
    'editorGhostText.border': '#00000000',
    'editorStickyScroll.background': light ? ui.chrome : ui.surface,
    'editorStickyScroll.border': borderSoft,
    'editorStickyScroll.shadow': shadow,
    'editorStickyScrollHover.background': ui.raised,
    'editorWatermark.foreground': a(ui.comment, 0.7),

    /* bracket pair colourisation — six steps around the wheel, all at the
       same lightness so nesting never changes how loud the code looks */
    'editorBracketHighlight.foreground1': base.gold,
    'editorBracketHighlight.foreground2': base.rose,
    'editorBracketHighlight.foreground3': base.azure,
    'editorBracketHighlight.foreground4': base.green,
    'editorBracketHighlight.foreground5': base.violet,
    'editorBracketHighlight.foreground6': base.teal,
    'editorBracketHighlight.unexpectedBracket.foreground': status.error,
    'editorBracketPairGuide.activeBackground1': a(base.gold, 0.55),
    'editorBracketPairGuide.activeBackground2': a(base.rose, 0.55),
    'editorBracketPairGuide.activeBackground3': a(base.azure, 0.55),
    'editorBracketPairGuide.activeBackground4': a(base.green, 0.55),
    'editorBracketPairGuide.activeBackground5': a(base.violet, 0.55),
    'editorBracketPairGuide.activeBackground6': a(base.teal, 0.55),
    'editorBracketPairGuide.background1': a(base.gold, 0.16),
    'editorBracketPairGuide.background2': a(base.rose, 0.16),
    'editorBracketPairGuide.background3': a(base.azure, 0.16),
    'editorBracketPairGuide.background4': a(base.green, 0.16),
    'editorBracketPairGuide.background5': a(base.violet, 0.16),
    'editorBracketPairGuide.background6': a(base.teal, 0.16),

    /* ── diagnostics ──────────────────────────────────────────────────── */
    'editorError.foreground': status.error,
    'editorError.background': a(status.error, 0.07),
    'editorWarning.foreground': status.warning,
    'editorWarning.background': a(status.warning, 0.07),
    'editorInfo.foreground': status.info,
    'editorInfo.background': a(status.info, 0.06),
    'editorHint.foreground': a(base.teal, 0.75),
    'problemsErrorIcon.foreground': status.error,
    'problemsWarningIcon.foreground': status.warning,
    'problemsInfoIcon.foreground': status.info,

    /* ── gutter & overview ruler ──────────────────────────────────────── */
    'editorGutter.background': ui.editor,
    'editorGutter.addedBackground': a(status.success, 0.85),
    'editorGutter.modifiedBackground': a(base.gold, 0.85),
    'editorGutter.deletedBackground': a(status.error, 0.85),
    'editorGutter.commentRangeForeground': a(ui.subtle, 0.6),
    'editorGutter.commentGlyphForeground': ui.comment,
    'editorGutter.foldingControlForeground': ui.subtle,
    'editorOverviewRuler.background': ui.editor,
    'editorOverviewRuler.border': '#00000000',
    'editorOverviewRuler.findMatchForeground': a(base.amber, 0.65),
    'editorOverviewRuler.rangeHighlightForeground': a(base.violet, 0.45),
    'editorOverviewRuler.selectionHighlightForeground': a(base.azure, 0.45),
    'editorOverviewRuler.wordHighlightForeground': a(base.violet, 0.45),
    'editorOverviewRuler.wordHighlightStrongForeground': a(base.green, 0.45),
    'editorOverviewRuler.bracketMatchForeground': a(base.teal, 0.5),
    'editorOverviewRuler.addedForeground': a(status.success, 0.65),
    'editorOverviewRuler.modifiedForeground': a(base.gold, 0.65),
    'editorOverviewRuler.deletedForeground': a(status.error, 0.65),
    'editorOverviewRuler.errorForeground': status.error,
    'editorOverviewRuler.warningForeground': status.warning,
    'editorOverviewRuler.infoForeground': status.info,
    'editorOverviewRuler.commonContentForeground': a(ui.subtle, 0.35),
    'editorOverviewRuler.currentContentForeground': a(base.azure, 0.4),
    'editorOverviewRuler.incomingContentForeground': a(base.violet, 0.4),

    /* ── minimap ──────────────────────────────────────────────────────── */
    'minimap.background': light ? a(ui.editor, 0.85) : ui.editor,
    'minimap.selectionHighlight': a(base.azure, 0.5),
    'minimap.selectionOccurrenceHighlight': a(base.azure, 0.3),
    'minimap.findMatchHighlight': a(base.amber, 0.7),
    'minimap.errorHighlight': status.error,
    'minimap.warningHighlight': status.warning,
    'minimap.infoHighlight': status.info,
    'minimap.foregroundOpacity': '#000000c0',
    'minimapSlider.background': a(ui.subtle, 0.14),
    'minimapSlider.hoverBackground': a(ui.subtle, 0.22),
    'minimapSlider.activeBackground': a(ui.subtle, 0.3),
    'minimapGutter.addedBackground': a(status.success, 0.8),
    'minimapGutter.modifiedBackground': a(base.gold, 0.8),
    'minimapGutter.deletedBackground': a(status.error, 0.8),

    /* ── widgets: find, hover, suggest, peek ──────────────────────────── */
    'editorWidget.background': ui.overlay,
    'editorWidget.foreground': ui.fg,
    'editorWidget.border': border,
    'editorWidget.resizeBorder': a(base.rose, 0.6),
    'editorHoverWidget.background': ui.overlay,
    'editorHoverWidget.foreground': ui.fg,
    'editorHoverWidget.border': border,
    'editorHoverWidget.highlightForeground': bright.rose,
    'editorHoverWidget.statusBarBackground': a(ui.raised, 0.7),
    'editorSuggestWidget.background': ui.overlay,
    'editorSuggestWidget.foreground': ui.fg,
    'editorSuggestWidget.border': border,
    'editorSuggestWidget.selectedBackground': a(base.violet, light ? 0.16 : 0.2),
    'editorSuggestWidget.selectedForeground': ui.bright,
    'editorSuggestWidget.selectedIconForeground': bright.violet,
    'editorSuggestWidget.highlightForeground': bright.rose,
    'editorSuggestWidget.focusHighlightForeground': bright.rose,
    'editorSuggestWidgetStatus.foreground': ui.comment,
    'editorMarkerNavigation.background': ui.overlay,
    'editorMarkerNavigationError.background': status.error,
    'editorMarkerNavigationError.headerBackground': p.mix(ui.overlay, status.error, 0.16),
    'editorMarkerNavigationWarning.background': status.warning,
    'editorMarkerNavigationWarning.headerBackground': p.mix(ui.overlay, status.warning, 0.16),
    'editorMarkerNavigationInfo.background': status.info,
    'editorMarkerNavigationInfo.headerBackground': p.mix(ui.overlay, status.info, 0.16),
    'peekView.border': a(base.violet, 0.65),
    'peekViewEditor.background': light ? ui.raised : a(ui.deep, 0.45),
    'peekViewEditor.matchHighlightBackground': a(base.amber, 0.3),
    'peekViewEditor.matchHighlightBorder': a(base.amber, 0.6),
    'peekViewEditorGutter.background': light ? ui.raised : a(ui.deep, 0.45),
    'peekViewEditorStickyScroll.background': light ? ui.raised : a(ui.deep, 0.45),
    'peekViewResult.background': ui.surface,
    'peekViewResult.fileForeground': ui.fg,
    'peekViewResult.lineForeground': ui.comment,
    'peekViewResult.matchHighlightBackground': a(base.amber, 0.3),
    'peekViewResult.selectionBackground': a(base.violet, 0.2),
    'peekViewResult.selectionForeground': ui.bright,
    'peekViewTitle.background': ui.surface,
    'peekViewTitleDescription.foreground': ui.comment,
    'peekViewTitleLabel.foreground': ui.bright,

    /* ── diffs & merges ───────────────────────────────────────────────── */
    'diffEditor.insertedTextBackground': a(status.success, light ? 0.14 : 0.13),
    'diffEditor.insertedLineBackground': a(status.success, light ? 0.09 : 0.08),
    'diffEditor.removedTextBackground': a(status.error, light ? 0.14 : 0.14),
    'diffEditor.removedLineBackground': a(status.error, light ? 0.09 : 0.08),
    'diffEditor.insertedTextBorder': '#00000000',
    'diffEditor.removedTextBorder': '#00000000',
    'diffEditor.border': borderSoft,
    'diffEditor.diagonalFill': a(ui.subtle, 0.16),
    'diffEditor.unchangedRegionBackground': ui.surface,
    'diffEditor.unchangedRegionForeground': ui.comment,
    'diffEditor.unchangedCodeBackground': a(ui.subtle, 0.06),
    'diffEditorOverview.insertedForeground': a(status.success, 0.6),
    'diffEditorOverview.removedForeground': a(status.error, 0.6),
    'merge.currentHeaderBackground': a(base.azure, 0.3),
    'merge.currentContentBackground': a(base.azure, 0.12),
    'merge.incomingHeaderBackground': a(base.violet, 0.3),
    'merge.incomingContentBackground': a(base.violet, 0.12),
    'merge.commonHeaderBackground': a(ui.subtle, 0.25),
    'merge.commonContentBackground': a(ui.subtle, 0.1),
    'merge.border': '#00000000',
    'mergeEditor.change.background': a(status.success, 0.1),
    'mergeEditor.change.word.background': a(status.success, 0.2),
    'mergeEditor.conflict.unhandledUnfocused.border': a(status.warning, 0.5),
    'mergeEditor.conflict.unhandledFocused.border': status.warning,
    'mergeEditor.conflict.handledUnfocused.border': a(status.success, 0.3),
    'mergeEditor.conflict.handledFocused.border': a(status.success, 0.6),
    'mergeEditor.conflict.handled.minimapOverViewRuler': a(status.success, 0.6),
    'mergeEditor.conflict.unhandled.minimapOverViewRuler': status.warning,

    /* ── panel, terminal, output ──────────────────────────────────────── */
    'panel.background': ui.surface,
    'panel.border': borderSoft,
    'panel.dropBorder': base.rose,
    'panelTitle.activeBorder': base.rose,
    'panelTitle.activeForeground': ui.bright,
    'panelTitle.inactiveForeground': a(ui.dim, 0.6),
    'panelTitle.border': borderSoft,
    'panelSection.border': borderSoft,
    'panelSection.dropBackground': a(base.violet, 'soft'),
    'panelSectionHeader.background': a(ui.deep, 0.3),
    'panelSectionHeader.foreground': ui.fg,
    'panelInput.border': border,
    'panelStickyScroll.background': ui.surface,
    'panelStickyScroll.border': borderSoft,
    'outputView.background': ui.surface,
    'debugConsole.infoForeground': base.azure,
    'debugConsole.warningForeground': status.warning,
    'debugConsole.errorForeground': status.error,
    'debugConsole.sourceForeground': ui.comment,
    'debugConsoleInputIcon.foreground': base.rose,

    /* ── status bar ───────────────────────────────────────────────────── */
    'statusBar.background': ui.chrome,
    'statusBar.foreground': ui.dim,
    'statusBar.border': borderSoft,
    'statusBar.debuggingBackground': light ? base.amber : muted.amber,
    'statusBar.debuggingForeground': onAccent,
    'statusBar.debuggingBorder': '#00000000',
    'statusBar.noFolderBackground': ui.chrome,
    'statusBar.noFolderForeground': ui.dim,
    'statusBar.noFolderBorder': borderSoft,
    'statusBar.focusBorder': a(base.rose, 0.6),
    'statusBarItem.activeBackground': a(ui.subtle, 0.3),
    'statusBarItem.hoverBackground': a(ui.subtle, 0.18),
    'statusBarItem.hoverForeground': ui.bright,
    'statusBarItem.focusBorder': a(base.rose, 0.6),
    'statusBarItem.prominentBackground': a(ui.subtle, 0.22),
    'statusBarItem.prominentForeground': ui.bright,
    'statusBarItem.prominentHoverBackground': a(ui.subtle, 0.34),
    'statusBarItem.remoteBackground': a(base.violet, light ? 0.18 : 0.22),
    'statusBarItem.remoteForeground': bright.violet,
    'statusBarItem.remoteHoverBackground': a(base.violet, 0.3),
    'statusBarItem.remoteHoverForeground': ui.bright,
    'statusBarItem.errorBackground': a(status.error, light ? 0.16 : 0.2),
    'statusBarItem.errorForeground': light ? status.error : bright.coral,
    'statusBarItem.errorHoverBackground': a(status.error, 0.3),
    'statusBarItem.warningBackground': a(status.warning, light ? 0.16 : 0.2),
    'statusBarItem.warningForeground': light ? status.warning : bright.amber,
    'statusBarItem.warningHoverBackground': a(status.warning, 0.3),
    'statusBarItem.compactHoverBackground': a(ui.subtle, 0.3),
    'statusBarItem.offlineBackground': a(status.error, 0.22),
    'statusBarItem.offlineForeground': light ? status.error : bright.coral,

    /* ── title bar, menus, command centre ─────────────────────────────── */
    'titleBar.activeBackground': ui.chrome,
    'titleBar.activeForeground': ui.dim,
    'titleBar.inactiveBackground': ui.chrome,
    'titleBar.inactiveForeground': a(ui.dim, 0.5),
    'titleBar.border': borderSoft,
    'commandCenter.foreground': ui.dim,
    'commandCenter.activeForeground': ui.bright,
    'commandCenter.background': a(ui.subtle, 0.1),
    'commandCenter.activeBackground': a(ui.subtle, 0.2),
    'commandCenter.border': borderSoft,
    'commandCenter.activeBorder': a(base.rose, 0.5),
    'commandCenter.inactiveForeground': a(ui.dim, 0.5),
    'commandCenter.inactiveBorder': borderSoft,
    'menu.background': ui.overlay,
    'menu.foreground': ui.fg,
    'menu.selectionBackground': a(base.violet, 0.22),
    'menu.selectionForeground': ui.bright,
    'menu.selectionBorder': '#00000000',
    'menu.separatorBackground': a(ui.subtle, 0.35),
    'menu.border': border,
    'menubar.selectionBackground': a(ui.subtle, 0.2),
    'menubar.selectionForeground': ui.bright,
    'menubar.selectionBorder': '#00000000',
    'toolbar.hoverBackground': a(ui.subtle, 0.2),
    'toolbar.hoverOutline': '#00000000',
    'toolbar.activeBackground': a(ui.subtle, 0.3),
    'profileBadge.background': a(base.rose, 0.28),
    'profileBadge.foreground': bright.rose,

    /* ── quick input / command palette ────────────────────────────────── */
    'quickInput.background': ui.overlay,
    'quickInput.foreground': ui.fg,
    'quickInputList.focusBackground': a(base.violet, light ? 0.16 : 0.2),
    'quickInputList.focusForeground': ui.bright,
    'quickInputList.focusIconForeground': bright.violet,
    'quickInputTitle.background': a(ui.deep, 0.35),
    'pickerGroup.border': a(ui.subtle, 0.3),
    'pickerGroup.foreground': bright.rose,
    'keybindingLabel.background': a(ui.subtle, 0.16),
    'keybindingLabel.foreground': ui.fg,
    'keybindingLabel.border': a(ui.subtle, 0.3),
    'keybindingLabel.bottomBorder': a(ui.subtle, 0.4),
    'keybindingTable.headerBackground': a(ui.raised, 0.6),
    'keybindingTable.rowsBackground': a(ui.raised, 0.35),

    /* ── notifications & banners ──────────────────────────────────────── */
    'notificationCenter.border': border,
    'notificationCenterHeader.background': ui.surface,
    'notificationCenterHeader.foreground': ui.fg,
    'notificationToast.border': border,
    'notifications.background': ui.overlay,
    'notifications.foreground': ui.fg,
    'notifications.border': borderSoft,
    'notificationLink.foreground': base.azure,
    'notificationsErrorIcon.foreground': status.error,
    'notificationsWarningIcon.foreground': status.warning,
    'notificationsInfoIcon.foreground': status.info,
    'banner.background': ui.overlay,
    'banner.foreground': ui.fg,
    'banner.iconForeground': base.violet,

    /* ── source control ───────────────────────────────────────────────── */
    'gitDecoration.addedResourceForeground': status.success,
    'gitDecoration.modifiedResourceForeground': base.gold,
    'gitDecoration.deletedResourceForeground': status.error,
    'gitDecoration.renamedResourceForeground': base.teal,
    'gitDecoration.stageModifiedResourceForeground': base.gold,
    'gitDecoration.stageDeletedResourceForeground': status.error,
    'gitDecoration.untrackedResourceForeground': base.green,
    'gitDecoration.ignoredResourceForeground': a(ui.comment, 0.65),
    'gitDecoration.conflictingResourceForeground': base.rose,
    'gitDecoration.submoduleResourceForeground': base.violet,
    'scmGraph.historyItemHoverLabelForeground': ui.bright,
    'scmGraph.foreground1': base.rose,
    'scmGraph.foreground2': base.azure,
    'scmGraph.foreground3': base.green,
    'scmGraph.foreground4': base.gold,
    'scmGraph.foreground5': base.violet,
    'scmGraph.historyItemHoverAdditionsForeground': status.success,
    'scmGraph.historyItemHoverDeletionsForeground': status.error,
    'scmGraph.historyItemRefColor': base.azure,
    'scmGraph.historyItemRemoteRefColor': base.violet,
    'scmGraph.historyItemBaseRefColor': base.rose,

    /* ── debug ────────────────────────────────────────────────────────── */
    'debugToolBar.background': ui.overlay,
    'debugToolBar.border': border,
    'debugIcon.breakpointForeground': status.error,
    'debugIcon.breakpointDisabledForeground': a(status.error, 0.4),
    'debugIcon.breakpointUnverifiedForeground': a(ui.subtle, 0.8),
    'debugIcon.breakpointCurrentStackframeForeground': base.gold,
    'debugIcon.breakpointStackframeForeground': base.amber,
    'debugIcon.startForeground': status.success,
    'debugIcon.pauseForeground': base.azure,
    'debugIcon.stopForeground': status.error,
    'debugIcon.disconnectForeground': status.error,
    'debugIcon.restartForeground': status.success,
    'debugIcon.stepOverForeground': base.violet,
    'debugIcon.stepIntoForeground': base.violet,
    'debugIcon.stepOutForeground': base.violet,
    'debugIcon.continueForeground': base.violet,
    'debugIcon.stepBackForeground': base.violet,
    'editor.stackFrameHighlightBackground': a(base.gold, 0.16),
    'editor.focusedStackFrameHighlightBackground': a(status.success, 0.16),
    'debugView.stateLabelBackground': a(ui.subtle, 0.2),
    'debugView.stateLabelForeground': ui.fg,
    'debugView.valueChangedHighlight': a(base.azure, 0.4),
    'debugView.exceptionLabelBackground': a(status.error, 0.25),
    'debugView.exceptionLabelForeground': ui.bright,
    'debugTokenExpression.name': base.coral,
    'debugTokenExpression.value': ui.dim,
    'debugTokenExpression.string': base.green,
    'debugTokenExpression.boolean': base.violet,
    'debugTokenExpression.number': base.amber,
    'debugTokenExpression.error': status.error,
    'debugTokenExpression.type': base.gold,

    /* ── testing ──────────────────────────────────────────────────────── */
    'testing.iconFailed': status.error,
    'testing.iconErrored': status.error,
    'testing.iconPassed': status.success,
    'testing.iconQueued': base.gold,
    'testing.iconSkipped': ui.comment,
    'testing.iconUnset': ui.subtle,
    'testing.runAction': status.success,
    'testing.message.error.decorationForeground': status.error,
    'testing.message.error.lineBackground': a(status.error, 0.12),
    'testing.message.info.decorationForeground': ui.comment,
    'testing.message.info.lineBackground': a(base.azure, 0.08),
    'testing.peekBorder': a(status.error, 0.6),
    'testing.peekHeaderBackground': p.mix(ui.overlay, status.error, 0.14),
    'testing.coveredBackground': a(status.success, 0.12),
    'testing.coveredBorder': a(status.success, 0.3),
    'testing.coveredGutterBackground': a(status.success, 0.55),
    'testing.uncoveredBackground': a(status.error, 0.1),
    'testing.uncoveredBorder': a(status.error, 0.28),
    'testing.uncoveredBranchBackground': a(status.warning, 0.16),
    'testing.uncoveredGutterBackground': a(status.error, 0.4),
    'testing.coverCountBadgeBackground': a(base.violet, 0.25),
    'testing.coverCountBadgeForeground': bright.violet,

    /* ── notebooks ────────────────────────────────────────────────────── */
    'notebook.editorBackground': ui.editor,
    'notebook.cellBorderColor': borderSoft,
    'notebook.cellEditorBackground': light ? ui.raised : ui.surface,
    'notebook.cellHoverBackground': a(ui.raised, 0.5),
    'notebook.cellStatusBarItemHoverBackground': a(ui.subtle, 0.2),
    'notebook.cellToolbarSeparator': borderSoft,
    'notebook.focusedCellBackground': a(ui.raised, 0.35),
    'notebook.focusedCellBorder': a(base.rose, 0.6),
    'notebook.focusedEditorBorder': a(base.rose, 0.5),
    'notebook.inactiveFocusedCellBorder': a(ui.subtle, 0.4),
    'notebook.outputContainerBackgroundColor': a(ui.raised, 0.4),
    'notebook.outputContainerBorderColor': borderSoft,
    'notebook.selectedCellBackground': a(ui.raised, 0.5),
    'notebook.selectedCellBorder': a(ui.subtle, 0.4),
    'notebook.symbolHighlightBackground': a(base.amber, 0.14),
    'notebookScrollbarSlider.background': a(ui.subtle, 0.24),
    'notebookScrollbarSlider.hoverBackground': a(ui.subtle, 0.4),
    'notebookScrollbarSlider.activeBackground': a(base.rose, 0.4),
    'notebookStatusErrorIcon.foreground': status.error,
    'notebookStatusRunningIcon.foreground': base.azure,
    'notebookStatusSuccessIcon.foreground': status.success,

    /* ── charts (used by profilers & extensions) ──────────────────────── */
    'charts.foreground': ui.fg,
    'charts.lines': a(ui.subtle, 0.4),
    'charts.red': base.coral,
    'charts.blue': base.azure,
    'charts.yellow': base.gold,
    'charts.orange': base.amber,
    'charts.green': base.green,
    'charts.purple': base.violet,
    'chart.line': base.azure,
    'chart.axis': a(ui.subtle, 0.5),
    'chart.guide': a(ui.subtle, 0.25),

    /* ── ports, remote, welcome ───────────────────────────────────────── */
    'ports.iconRunningProcessForeground': base.green,
    'walkThrough.embeddedEditorBackground': light ? ui.raised : ui.surface,
    'welcomePage.background': ui.editor,
    'welcomePage.progress.background': a(ui.subtle, 0.2),
    'welcomePage.progress.foreground': base.rose,
    'welcomePage.tileBackground': ui.surface,
    'welcomePage.tileHoverBackground': ui.raised,
    'welcomePage.tileBorder': borderSoft,

    /* ── settings editor ──────────────────────────────────────────────── */
    'settings.headerForeground': ui.bright,
    'settings.modifiedItemIndicator': base.rose,
    'settings.dropdownBackground': ui.overlay,
    'settings.dropdownForeground': ui.fg,
    'settings.dropdownBorder': border,
    'settings.dropdownListBorder': border,
    'settings.checkboxBackground': ui.overlay,
    'settings.checkboxForeground': ui.fg,
    'settings.checkboxBorder': border,
    'settings.textInputBackground': light ? ui.editor : a(ui.deep, 0.55),
    'settings.textInputForeground': ui.fg,
    'settings.textInputBorder': border,
    'settings.numberInputBackground': light ? ui.editor : a(ui.deep, 0.55),
    'settings.numberInputForeground': base.amber,
    'settings.numberInputBorder': border,
    'settings.focusedRowBackground': a(ui.raised, 0.5),
    'settings.focusedRowBorder': a(base.rose, 0.35),
    'settings.headerBorder': borderSoft,
    'settings.rowHoverBackground': a(ui.raised, 0.3),
    'settings.sashBorder': borderSoft,

    /* ── breadcrumbs ──────────────────────────────────────────────────── */
    'breadcrumb.foreground': a(ui.dim, 0.65),
    'breadcrumb.background': ui.editor,
    'breadcrumb.focusForeground': ui.fg,
    'breadcrumb.activeSelectionForeground': bright.rose,
    'breadcrumbPicker.background': ui.overlay,

    /* ── symbol icons (outline, suggest) ──────────────────────────────── */
    'symbolIcon.arrayForeground': base.amber,
    'symbolIcon.booleanForeground': base.violet,
    'symbolIcon.classForeground': base.gold,
    'symbolIcon.colorForeground': base.rose,
    'symbolIcon.constantForeground': base.amber,
    'symbolIcon.constructorForeground': base.violet,
    'symbolIcon.enumeratorForeground': base.gold,
    'symbolIcon.enumeratorMemberForeground': base.amber,
    'symbolIcon.eventForeground': base.coral,
    'symbolIcon.fieldForeground': base.coral,
    'symbolIcon.fileForeground': ui.fg,
    'symbolIcon.folderForeground': ui.fg,
    'symbolIcon.functionForeground': base.azure,
    'symbolIcon.interfaceForeground': base.gold,
    'symbolIcon.keyForeground': base.teal,
    'symbolIcon.keywordForeground': base.rose,
    'symbolIcon.methodForeground': base.azure,
    'symbolIcon.moduleForeground': base.gold,
    'symbolIcon.namespaceForeground': base.gold,
    'symbolIcon.nullForeground': base.violet,
    'symbolIcon.numberForeground': base.amber,
    'symbolIcon.objectForeground': base.gold,
    'symbolIcon.operatorForeground': base.teal,
    'symbolIcon.packageForeground': base.gold,
    'symbolIcon.propertyForeground': base.coral,
    'symbolIcon.referenceForeground': base.teal,
    'symbolIcon.snippetForeground': base.green,
    'symbolIcon.stringForeground': base.green,
    'symbolIcon.structForeground': base.gold,
    'symbolIcon.textForeground': ui.fg,
    'symbolIcon.typeParameterForeground': base.gold,
    'symbolIcon.unitForeground': base.amber,
    'symbolIcon.variableForeground': ui.fg,

    /* ── snippets & inline chat ───────────────────────────────────────── */
    'editor.snippetTabstopHighlightBackground': a(base.teal, 0.14),
    'editor.snippetTabstopHighlightBorder': a(base.teal, 0.35),
    'editor.snippetFinalTabstopHighlightBackground': a(base.rose, 0.14),
    'editor.snippetFinalTabstopHighlightBorder': a(base.rose, 0.4),
    'inlineChat.background': ui.overlay,
    'inlineChat.border': a(base.violet, 0.5),
    'inlineChat.shadow': shadow,
    'inlineChatInput.background': light ? ui.editor : a(ui.deep, 0.5),
    'inlineChatInput.border': border,
    'inlineChatInput.focusBorder': a(base.violet, 0.7),
    'inlineChatInput.placeholderForeground': ui.comment,
    'inlineChatDiff.inserted': a(status.success, 0.12),
    'inlineChatDiff.removed': a(status.error, 0.12),
    'chat.requestBorder': borderSoft,
    'chat.requestBackground': a(ui.raised, 0.4),
    'chat.slashCommandBackground': a(base.violet, 0.2),
    'chat.slashCommandForeground': bright.violet,
    'chat.avatarBackground': a(base.rose, 0.25),
    'chat.avatarForeground': bright.rose,
    'chat.editedFileForeground': base.gold,
  };
};
